services:
  api:
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/src
    image: "danielg9611/aid-api"

  streamlit:
    build: .
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api
    links:
      - api
    env_file:
      - .env
    volumes:
      - .:/src
    image: "danielg9611/aid-streamlit"
